#!/bin/sh
# Usage: script/bootstrap
# Initializes your environment for development

cd "$(dirname "$0")/.."

# git submodules
git submodule sync --quiet || exit $?
git submodule update --init || exit $?
git submodule foreach --recursive --quiet "git submodule sync --quiet && git submodule update --init" || exit $?
